name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      
    - name: Install AST extension
      run: sudo pecl install ast
      
    - name: Set AST extension
      run: echo "extension=ast" | sudo tee -a /etc/php/8.0/cli/php.ini

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Fix linting errors
      run: composer lint-fix
      
    - name: Set up static analyzer
      run: composer analyze-init
      
    - name: Run static analysis
      run: composer analyze

    - name: Run test suite
      env:
        XDEBUG_MODE: coverage
      run: composer run-script test

    - name: Upload coverage results to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: composer gen-coverage-badge

